### ISSUE TITLE
Allow setting message when registering payment

### ISSUE THREAD

**Issue by CherryDT** [SolidInvoice/SolidInvoice#1003]
**Is your feature request related to a problem? Please describe.**
When an external payment is manually registered using the "Pay now" button, there are only fields for payment method and amount but no additional notes/message field for saving payment details such as a payment transaction ID for future reference.

**Describe the solution you'd like**
I'd like there to be a "Message" field when registering a payment.

**Additional context**
I can see a column "Message" in the table after registering the payment, but it's empty and I don't have a way to set it... So I guess it shouldn't be too complicated to add it, as the field seemingly already exists in the DB? If I were to implement it myself, are there any gotchas to consider?

**Comment by pierredup** [comment]
The current message field is used to capture a message from the payment gateway after a payment has been made. Currently it's only used by paypal_express and is only populated when a payment fails, then it captures the failure details in the message field.

For this request, I would add 2 new fields: `transaction_id varchar(255)` and `notes text`.
The transaction_id can then be used to manually capture a transaction id, and the notes fields can be used for custom information when manually capturing a payment.

> If I were to implement it myself, are there any gotchas to consider?

These additional fields should only be added when a payment is manually captured by an admin user, and not when the client initiates the payment. There are already a check in place to ensure a user is set when adding specific fields, so these new fields can be added in the same condition

https://github.com/SolidInvoice/SolidInvoice/blob/b24e9aafb39e9628ccef9649b9daeb997180dc37/src/PaymentBundle/Form/Type/PaymentType.php#L77

**Comment by CherryDT** [comment]
When registering payment is allowed in the API, it should also be possible to add the comment.
