### ISSUE TITLE
Creating database schema Issue, SQLSTATE[HY000]: General error: 1553

### ISSUE THREAD

**Issue by damalis** [SolidInvoice/SolidInvoice#1042]
**Describe the bug**
When I launch the application it goes through setup and fails after entering credentials for the database to finish config.

**To Reproduce**
1. Go to ' launch the application and brings up 'System Requirement Check'
![image](https://github.com/SolidInvoice/SolidInvoice/assets/11361779/54c63422-ff66-4b61-9c69-8f501d78d94c)

2. Click on 'Next and brings you to the Database Config page .'
3. Enter all of the information for database configuration
4. Click on next and get error

![image](https://github.com/SolidInvoice/SolidInvoice/assets/11361779/910e164d-5e83-43df-a23c-9fb9fa095187)

Desktop (please complete the following information):

OS: [Windows 11 Home Single Language, 21H2]
Browser [chrome]
Version [124.0.6367.91 (Official Build) (64-bit)]

XAMPP: [ApacheFriends XAMPP Version 8.2.4]
   Apache 2.4.56
  MariaDB 10.4.28
  PHP 8.2.4 (VS16 X86 64bit thread safe) + PEAR
  phpMyAdmin 5.2.1

**Comment by pierredup** [comment]
@damalis Thanks for the report. The `2.3.x` branch is currently under active development and not stable. If you want to run a stable version of SolidInvoice, then I would recommend downloading one of the archive packages at https://github.com/SolidInvoice/SolidInvoice/releases/latest, or running the latest version using Docker at https://hub.docker/com/r/solidinvoice/solidinvoice.
