### ISSUE TITLE
Issue with Quote Creation

### ISSUE THREAD

**Issue by luchianenco** [SolidInvoice/SolidInvoice#1094]
**Describe the bug**
After installation of the SolidInvoice I have successfully connected it with DB and created all schemas. I had successfully created user and logged in. I have successfully created new client but when I wanna create a new quote I can not add items to the quote as I get jquery error in browser - tried out Safari and Chome

**To Reproduce**
1. Create a new clien
2. Go to Create a Quote
3. You will see only Terms & Notes fields, but other files are not shown
4. Error in the browser

993.1dbf1f15.js:2 Uncaught TypeError: t is not a function
    at M.i._renderHtml (257.ede149a1.js:2:55652)
    at M.i._renderTemplate (257.ede149a1.js:2:55131)
    at M.i.render (257.ede149a1.js:2:70537)
    at ht (257.ede149a1.js:2:61752)
    at 257.ede149a1.js:2:79871
    at Function.We (257.ede149a1.js:2:291949)
    at M.i._getBuffer (257.ede149a1.js:2:79851)
    at M.i._renderChildren (257.ede149a1.js:2:79672)
    at M.i.filter (257.ede149a1.js:2:77860)
    at M.i.sort (257.ede149a1.js:2:77077)

**Expected behavior**
Items for quote creation should be available and visible

**Screenshots**
<img width="1725" alt="Screenshot 2024-06-24 at 13 11 54" src="https://github.com/SolidInvoice/SolidInvoice/assets/3841383/1d32f244-deeb-4a48-9afe-1f0a7c506234">

**Desktop (please complete the following information):**
- OS: mcbook 
- Browser : Chrome, Safari
- Chrome: 126.0.6478.114 , Safari: 17:5

**Additional context**
I did installation locally on MacBook in docker and also on the server - the behavior is the same

**Comment by pierredup** [comment]
@luchianenco Which version of SolidInvoice are you using?

Do you have any browser extensions that might be interfering? The item in the network tab doesn't look like a script that SolidInvoice loads (`ads.png.test-adblockers-exists`), this might be something that's loaded from a browser extension.

Does this happen when you load the page in incognito mode?

**Comment by pierredup** [comment]
@luchianenco , Actually, the same error happens with the latest 2.3.x branch, which is still under active development. I would suggest you install one of the [2.2.x releases](https://github.com/SolidInvoice/SolidInvoice/releases) instead

**Comment by luchianenco** [comment]
@pierredup thanks for the hint - yes I have used the last tag - but switch to the previous one helped

**Comment by pierredup** [comment]
@luchianenco Thanks for confirming. Closing this. If any other issue comes up, please feel free to open a new issue
