### ISSUE TITLE
Option to set invoice to be paid and save invoice without sending it to the customer

### ISSUE THREAD

**Issue by julianvdh** [SolidInvoice/SolidInvoice#1100]
There is no option to set the invoice to be paid within the panel. Only the customer can do this.

Option to create an invoice an add it to a user without sending it with email to them.

**Comment by pierredup** [comment]
Hi @julianvdh , thanks for the report.

> There is no option to set the invoice to be paid within the panel. Only the customer can do this.

when viewing an Invoice, there is an option `Pay Now`, where you can capture a payment for the invoice. You can use one of the offline payment gateways (Cash, Bank transfer etc) to capture a payment, which will then mark the invoice as paid

> Option to create an invoice an add it to a user without sending it with email to them.

This is currently available in the 2.3.x branch, and will be part of the upcoming 2.3 release

**Comment by julianvdh** [comment]
Ah i see, thank you!
