### ISSUE TITLE
Ability to set configuration by environment variables

### ISSUE THREAD

**Issue by rf152** [SolidInvoice/SolidInvoice#1263]
**Describe the solution you'd like**
I use kubernetes, and it would be very helpful to be able to configure the application by environment variables passed into the container. This allows the configuration to be done at the k8s level rather than within the application itself.

I believe SolidInvoice is based on laravel, which I believe has the ability to configure via environment variables (the base laravel using the .env file).

Happy to help implement both this and the other feature request I raised, but might need a bit of direction as I haven't used Laravel since v5 ish.

**Comment by pierredup** [comment]
This is already possible, since SolidInvoice writes configuration values to a file which then gets loaded as env variables.
You would need to set the following env variables on the containers:

```
database_host
database_port
database_name
database_user
database_password
database_driver
database_version
locale
installed
secret
```

here's an example with values:

```
database_host=db-host
database_port=3306
database_name=solidinvoice
database_user=root
database_password=password
database_driver=pdo_mysql
database_version=8.3.0
locale=en_US
installed=2024-05-06T18:34:11+00:00
secret=def00000e903801a2e80dac29409b557807b940827be175a983600a969e7ec8b347c654d88884c091922d495147770583a04f3afb11433d91701598794214d39d3f0b474
```

> I believe SolidInvoice is based on laravel

SolidInvoice is based on Symfony.

> Happy to help implement both this and the other feature request I raised, but might need a bit of direction

I would be happy to accept a PR, let me know if you have any specific questions

**Comment by rf152** [comment]
Yep, I've just confirmed this works for these variables.
