### ISSUE TITLE
Select default client and contact when creating a new quote or invoice

### ISSUE THREAD

**Issue by pierredup** [SolidInvoice/SolidInvoice#138]
When creating a new quote/invoice, if there is only one client, select it by default.
And if a client only have one contact, select that contact by default

**Comment by mohitjawanjal** [comment]
Can I claim this issue to work on it?

**Comment by pierredup** [comment]
@mohitjawanjal sure, go ahead!

**Comment by LillyMich** [comment]
Hi, I see that this issue is still not solved. I would like to work on it, can I?
