### ISSUE TITLE
Docker link is not working anymore.

### ISSUE THREAD

**Issue by olmobuining** [SolidInvoice/SolidInvoice#194]
I tried to go to the docker link in the readme file, but it gives a 404. I would gladly change it (PR), but I can't find the docker link for it.

**Comment by stkrzysiak** [comment]
Could this be the docker [link](https://hub.docker.com/r/csbill/csbill/)?  There seems to [have been a name change. ](https://twitter.com/pdples/status/899971625122242566)

**Comment by pierredup** [comment]
@stkrzysiak yes that is the old name (and old link for docker). I haven't published the new image for version 2 under the new name yet, but will get it done soon

**Comment by pierredup** [comment]
The docker image has been pushed to https://hub.docker.com/r/solidinvoice/solidinvoice/
