### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by hounded** [SolidInvoice/SolidInvoice#211]
I really want this to work, why did you make it so hard?

## Require php7.2

```
Deprecated: Function create_function() is deprecated in /var/www/symfony/var/SymfonyRequirements.php on line 540
```
A quick google shows that something is missing with 7.2, why require 7.2 if you can't get stability? 

## Install warning and js failure
Now i'm not very savy with js, and would rather not scratch around and fix this

```
Loading failed for the <script> with source “http://localhost/js/fos_js_routes.js?2.0.0-alpha2”.
process:1
Error: Script error for "fos_routing_data", needed by: routing
http://requirejs.org/docs/errors.html#scripterror
require.js:168:17
```
Get this after I input the details for the db and the smtp, which I already set in params? 

anyway by the time I did some research for this comment I traced it down to this
```twig 
{% if app.debug %}
     'fos_routing_data': '{{ path('fos_js_routing_js', {'callback': 'define'}) }}',
      'translation_data': '{{ path('bazinga_jstranslation_js', {'locales' : locale}) }}'
 {% else %} 
       'translation_data': '{{ asset('js/translations/' ~ locale ~ '.js') }}'
{% endif %}
```

I added fos_routing_data so it is available in the app.php controller not just the app_dev.php controller

Not sure the adverse affect but I got it installed and then alot of the issues went away
also had to add the translation_data, other wise I couldn't add items to the invoice. 

## Save a draft
finally got the invoice working input some data save as a draft
```
500 Internal Server Error

The following error occurred:

Type error: json_decode() expects parameter 1 to be string, null given
```

```
in src/SettingsBundle/Twig/Extension/SettingsExtension.php (line 53) 
```
## try to delete a client
```uncaught exception: Callback specified for event modal:save is not a valid callback```

I really appreciate what you are trying to do here, but do you think you can test to see it works before deploying?

**Comment by hounded** [comment]
Cheers for the quick reply!, I have a full docker-compose configuration set up to work with the master branch I will push and share with you once I get everything running

**Comment by hounded** [comment]
It is running smoooth, I will no doubt be contributing to this project, what a great job!!

**Comment by pierredup** [comment]
Thanks!
