### ISSUE TITLE
Need some help for developer installation/

### ISSUE THREAD

**Issue by carlcheunghk** [SolidInvoice/SolidInvoice#225]
Hi, I am a newbie in programming and I have background in accounting. I would like to contribute in this project. Sadly, I have trouble to install.
I have learnt a bit C, Java and Python. This is the first time I learn PHP and Nodejs(for this project). So my trouble could be related to incomplete install.
I am using Ubuntu 18.04
I can confirm I have composer, php and nodjs+npm installed.
When I follow develop installing instruction:
`php bin/console assets:install --symlink web
`
The above command shows up the following error:
```
PHP Warning:  require(/home/carl/SolidInvoice/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/carl/SolidInvoice/app/autoload.php on line 18
PHP Fatal error:  require(): Failed opening required '/home/carl/SolidInvoice/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/carl/SolidInvoice/app/autoload.php on line 18
```
I suspect it is related to $PATH which I do not have good understanding.
I try
` echo $PATH
`
output is
`/home/carl/anaconda3/bin:/home/carl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`
I cannot see :/usr/share/php. Does it mean that I just need to add php? If so, how?
P.S.: when I use `php -v` I can have version output.
Thanks!

**Comment by pierredup** [comment]
Hi @carlcheunghk!

Thanks for your interest in the project.

It seems like the vendor packages hasn't been installed in your system yet.
Have you run `composer install` (or `php composer.phar install` if you downloaded the composer.phar file)?
Can you let me know what output you get after running one of the commands?

**Comment by carlcheunghk** [comment]
You are right about composer install failed. 
I have been trying to fix it myself. Unfortunately, I can't. 
Inside folder ~/SolidInvoice, I ran `composer install` and get the following error.
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/routing v4.1.6 -> satisfiable by symfony/routing[v4.1.6].
    - don't install symfony/symfony v3.4.17|don't install symfony/routing v4.1.6
    - Installation request for symfony/symfony v3.4.17 -> satisfiable by symfony/symfony[v3.4.17].
```
I am able to identify that I lack symfony/routing package.
I then try to install it with 
`composer require symfony/routing
`
But I got bombed with errors : https://pastebin.com/eMVd09aA
The error tells me that I need solidworx/form-handler-bundle:1.0.0-rc3, I tried to install it but got error as well.
```
 composer require solidworx/form-handler-bundle:1.0.0-rc3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/routing v4.1.6
    - don't install symfony/symfony v3.4.17|don't install symfony/routing v4.1.6
    - don't install symfony/symfony v3.4.17|don't install symfony/routing v4.1.6
    - Installation request for symfony/routing (locked at v4.1.6) -> satisfiable by symfony/routing[v4.1.6].
    - Installation request for symfony/symfony (locked at v3.4.17) -> satisfiable by symfony/symfony[v3.4.17].

```

I then tried to install symfony with `sudo apt install php-symfony` I got it installed but when I run `composer install` I got errors again. I also found that Symfony do not recommend to install it this way.

I checked Symfony documentation. It appears that I need to create a project name like `composer create-project symfony/skeleton symphart` I got it successfully installed but obviously it is not relevant to  ~/SolidInvoice which I am trying to work with.

Currently my SolidInvoice folder has following items.
```
~/SolidInvoice$ ls
app        bin            composer.lock  CONTRIBUTING.md  features     History.md  package.json  phpunit.xml.dist  src       testem.json  travis      var  yarn.lock
behat.yml  composer.json  composer.phar  echo             Gulpfile.js  LICENSE     phpstan.neon  README.md         symphart  tests        UPGRADE.md  web

```
I completely ran out of ideas now. Any suggestions would be highly appreciated! Thanks!

**Comment by pierredup** [comment]
Thanks for the detailed report. There was a bug fixed in the latest version of composer (composer/composer#7764) that caused some issues when trying to install the dependencies.
I have a pushed a fix for this to the master branch. Please update your checkout with the latest changes and try installing the dependencies again

```
git pull origin master
composer install
```
