### ISSUE TITLE
"SOLIDINVOICE_ENV" environment variable is missing

### ISSUE THREAD

**Issue by alhiro** [SolidInvoice/SolidInvoice#260]
I am interesting in this project. WHen i am trying run command
php bin/console assets:install --symlink web
show display error "Fatal error: Uncaught RuntimeException: Environment is not set up correctly. "SOLIDINVOICE_ENV" environment variable is missing. in C:\xampp\htdocs\invoice\web\app.php:27 Stack trace: #0 {main} thrown in C:\xampp\htdocs\invoice\web\app.php on line 27

I have get error about environment variable is misssing.
How to fix this?

Thank you

**Comment by pierredup** [comment]
Thanks for reporting this. As part of the repository, there is a `.env.dist` file, which you can just rename to `.env`. This should fix the error for you (this file actually needs to be automatically created, but is broken currently. It will be fixed soon)

**Comment by alhiro** [comment]
It's Working now. But there is new item missing in web folder. No css file and others. I will create new issue.
Thank you.
