### ISSUE TITLE
API Tutorial

### ISSUE THREAD

**Issue by arfeen** [SolidInvoice/SolidInvoice#263]
Hi

Could not find any other place to post this question thats using this platform.

How could we consume SolidInvoice API ? Is there any tutorial online ?

**Comment by pierredup** [comment]
Hi @arfeen 

We are busy updating all the documentation to add more useful information, but this will take some time. To view some api documentation, you can navigate to `/api/docs` of your installed SolidInvoice instance. This should give you an overview of the available endpoints.
When you are logged, you can click on your username in the top menu, then choose `API Tokens`, to generate an authentication token to use with the api. When you make any calls to the api, you need to include the authentication token in the `X-API-TOKEN` header. An example on the command line, using curl to get a list of all the clients would look like this

```bash
$ curl -H 'X-API-TOKEN: {your-generated-api-token}' https://{your-solidinvoice-url}/api/client
```

I hope this gives you enough information to get started. If you have any questions, let me know.

**Comment by arfeen** [comment]
Thanks @pierredup I have got the documentation in /api/docs and I think this is quite enough.
Thank you for the help.
