### ISSUE TITLE
Symlink issue with nginx

### ISSUE THREAD

**Issue by psaikali** [SolidInvoice/SolidInvoice#269]
**Describe the bug**
I'm having JavaScript errors during the installation process, on the /install/process/ page. By inspecting my console, I notice that accessing the `/bundles/solidinvoicecore/js/lib/require.js?2.1.0-dev` returns a 403 error.

I did the `php bin/console assets:install --symlink web` command on my server successfully.

![Capture 2019-06-25 à 21 02 31](https://user-images.githubusercontent.com/1606655/60125666-930f9b80-978c-11e9-93c1-855afc29b9f2.jpg)

When trying to access the `require.js` file directly, I do NOT get a 404 but a Forbidden page (`Forbidden: You don't have permission to access /bundles/solidinvoicecore/js/lib/require.js on this server.`).

And my NGINX logs reveal this: 
```
".../web/bundles/solidinvoicecore/js/lib/require.js" failed (40: Too many levels of symbolic links), client: 109.190.201.84, server: ..., request: "GET /bundles/solidinvoicecore/js/lib/require.js?2.1.0-dev HTTP/2.0", host: "..."
```

Do you have any idea why this would happen, and how I could fix this please?
I'm not sure which command is run by the `assets:install` CLI command, so I'm not sure where to look at to fix this.

Thanks a lot for your help!

**Comment by pierredup** [comment]
Hi @psaikali

Can you try running the command without the `--symlink` flag?

```bash
$ php bin/console assets:install web
```

This should copy all the files to the relevant directories, instead of creating symlinks.

(Note that any changes you make to js or css files in the src directory, won't then reflect in the frontend, you will need to run the `assets:install` command again after any change)

**Comment by psaikali** [comment]
Yeah, thanks a lot @pierredup, ça a marché niquel :)

Maybe worth mentioning in the docs?

Cheers mate
