### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by coderboy-ss** [SolidInvoice/SolidInvoice#279]
http://solidinvoice.net/install/system_check

After the installtion at the time of system check I am stuck here...
Please some body give me suggestion to solve this...

I am working on 
OS: Windows 7
LAMP: XAMP for windows.
PHP VERSION : 7.3.1

![image](https://user-images.githubusercontent.com/53108285/61704068-92086480-ad60-11e9-82bc-e46abff5e5df.png)

**Comment by pierredup** [comment]
@coderboy-ss Can you scroll down to the bottom of the screen? There should be a button where you can continue to the next screen

**Comment by coderboy-ss** [comment]
no the page ended at this only no scrolling available on this page.

**Comment by coderboy-ss** [comment]
I had tried to reinstall all the symfony packages to solve the requirement issue but it doesn't working at all.

**Comment by Superigi** [comment]
Zoom out and it will appear at the bottom. The scrollbar is disabled on the page for some reason.

**Comment by coderboy-ss** [comment]
![solidinvoice_js_error](https://user-images.githubusercontent.com/53108285/62023108-10e02000-b1ed-11e9-9842-e2a93f922e89.png)
![solidinvoice_installation](https://user-images.githubusercontent.com/53108285/62023110-10e02000-b1ed-11e9-944c-61fef52791d9.png)

okay, I have reach to database installation page but it didn't creating any tabels I have waited upto 10 minutes and some js and fontawesome icons is not loading you can see that in images.

**Comment by pierredup** [comment]
I will investigate the scrollbar issue and see if I can replicate it and provide a fix. 

@coderboy-ss With the error on the database installation page, did you run `node_modules/.bin/gulp` after setting the site up? Or did you install from the archive from a release?

**Comment by coderboy-ss** [comment]
yes i have run node_modules/.bin/gulp after setting the site up but i didn't installed it from the release archive.

**Comment by Superigi** [comment]
I'd start again from scratch.


Start in your home directory and then:

- Clone the project (`git clone https://github.com/SolidInvoice/SolidInvoice.git` or get a release `wget https://github.com/SolidInvoice/SolidInvoice/releases/download/2.0.3/SolidInvoice-2.0.3.zip`)
- Enter the project directory (`cd SolidInvoice`)
- Let composer install vendor packages (`composer install`)
- Install web assets (`php bin/console assets:install --symlink web`)
- Let gulp build assets (`npm i gulp -g && gulp build`)
- *Now* move it to where your web server can utilize it and set permissions/owners.

Worked fine on Ubuntu 18.04.2 w/ Apache 2.4 on AWS

**Comment by pierredup** [comment]
@coderboy-ss can you please try again with the latest changes and let me know if you still experience any issues with the scrollbar

**Comment by coderboy-ss** [comment]
Okay ya sure i will try to install the application from scratch!

**Comment by coderboy-ss** [comment]
I tried to install the application again form scratch i followed all the instructions but only scrolling issue is fixed, again font awesome icons not loading, at requirement check page showing again all that requirement issues, and if i continue to next page after filling the database config page, Page showing Installing Schema Creating Database but nothing happens.

I think there is issue of OS because if it is working fine in Ubuntu then why not in Windows ( Wamp )?

**Comment by pierredup** [comment]
Thank you for the feedback. I will do some testing on Windows to find and fix the issue

**Comment by coderboy-ss** [comment]
Yupps sure thank you.

**Comment by amandaroark** [comment]
> Zoom out and it will appear at the bottom. The scrollbar is disabled on the page for some reason.



> I'd start again from scratch.
> 
> Start in your home directory and then:
> 
>     * Clone the project (`git clone https://github.com/SolidInvoice/SolidInvoice.git` or get a release `wget https://github.com/SolidInvoice/SolidInvoice/releases/download/2.0.3/SolidInvoice-2.0.3.zip`)
> 
>     * Enter the project directory (`cd SolidInvoice`)
> 
>     * Let composer install vendor packages (`composer install`)
> 
>     * Install web assets (`php bin/console assets:install --symlink web`)
> 
>     * Let gulp build assets (`npm i gulp -g && gulp build`)
> 
>     * _Now_ move it to where your web server can utilize it and set permissions/owners.
> 
> 
> Worked fine on Ubuntu 18.04.2 w/ Apache 2.4 on AWS

Hey there!

When I get to the step "Install Web Access" I keep getting this error: 

php bin/console assets:install --symlink web
PHP Warning:  require(/home/swxadmin/SolidInvoice/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/swxadmin/SolidInvoice/app/autoload.php on line 18
PHP Fatal error:  require(): Failed opening required '/home/swxadmin/SolidInvoice/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/swxadmin/SolidInvoice/app/autoload.php on line 18

Any recommendations? I have tried the download multiple times. Any advice would be amazing

**Comment by pierredup** [comment]
The latest changes in the master branch includes a few changes to improve the asset handling. This includes replacing Gulp and removes some of the manual commands that needs to be run. You're welcome to test it and let me know if you still experience any issues.

**Comment by baden03** [comment]
Installed from the latest .zip file... following assets are missing
![Screen Shot 2019-11-29 at 11 38 28](https://user-images.githubusercontent.com/835758/69859505-f3a38700-129c-11ea-9a94-57fd11f02e14.png)

**Comment by pierredup** [comment]
@baden03 Which zip did you download? The one at https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.0.3?
I just checked that version, and no assets are missing. It might be an issue with the web server rewrites. Can you please share which web server you are using and what your config looks like

**Comment by baden03** [comment]
@pierredup yes, the latest .zip file clearly linked to from https://solidinvoice.co/ under the download link. As you can see the .zip file does not contain a 'fonts' folder
![Screen Shot 2019-11-29 at 12 00 19](https://user-images.githubusercontent.com/835758/69860893-d8864680-129f-11ea-8c47-6d8aa900fc8d.png)

The main folder and it's contents has the correct owner:group and permissions on the web server.

**Comment by pierredup** [comment]
The fonts as other assets is inside the `web` folder, so you should set the web folder as your document root.
It might be an issue with the top level rewrites, I will investigate that, but in the mean time you can try using the web folder as the document root and let me know if there are still any issues

**Comment by baden03** [comment]
ah-ha... the web folder! This very important detail seems to be missing from the documentation. Thank you, I'll give it another try today.

**Comment by zahoormit** [comment]
can you make a step by step video on its installation in locahost using xampp and upload it on youtube

**Comment by pierredup** [comment]
@zahoormit Unfortunately I don't have access to a Windows computer, so making an installation video will only be targeted for Mac users. But I'll definitely look at improving the docs and make it more clear how to install.

**Comment by pierredup** [comment]
I'm closing this issue as I think all issues should be resolved. If there are still any issues with the installation, please feel free to re-open this.
