### ISSUE TITLE
Installing from the distribution package runs in dev mode with no javascript.

### ISSUE THREAD

**Issue by kevinlekiller** [SolidInvoice/SolidInvoice#282]
**Describe the bug**
I've installed SolidInvoice using the instructions here https://docs.solidinvoice.co/en/latest/guide/getting_started/downloading.html#installing-distribution-package

When going to http://localhost/app.php, I can go through the setup, everything looks good, the database gets created, no errors / warnings / etc.

When I get to the http://localhost/app.php/login page, there is no javascript and the symphony profiler is enabled.

I've tried the docker image and it does not have the same issue.

**To Reproduce**
1. Download the latest release of SolidInvoice / Extract the zip
2. Move the files to an appropriate location / set the correct permissions
3. Create an apache vhost based on the example https://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html#configuring-apache 
4. Launch a browser and go through the setup until you reach the login screen

**Expected behavior**
Expected to be in "production" mode with javascript enabled.

**Screenshots**

![Screenshot_20190805_195405](https://user-images.githubusercontent.com/1641964/62502223-2b516500-b7bc-11e9-9e7f-bcaadefa4263.jpg)

**Desktop (please complete the following information):**
 - Arch Linux / Apache
 - Firefox (new profile) / Chromium / Brave

**Comment by pierredup** [comment]
Thank you @kevinlekiller. I have rebuilt and uploaded the distribution package for the latest version to completely remove dev mode.

**Comment by kevinlekiller** [comment]
Thanks @pierredup !
