### ISSUE TITLE
Issues with Installation

### ISSUE THREAD

**Issue by Tepsiya** [SolidInvoice/SolidInvoice#289]
Using latest verion of SolidInvoice

When installing on Hosted environment - it passes the system check but when getting to DB setup it fails. 
DB connection is correct and **DB exists already**, but fails to create tables and schema. 

Note: in some hosted environments DB creation is handled only through admin page. 

to reproduce ..
create a table on mysql db and use this in the db setup and connection page. It will not create tables nor schema.

**Comment by pierredup** [comment]
@Tepsiya Do you perhaps have a screenshot of the error or can you please paste the error message that you are seeing?

Installing on an existing database shouldn't be an issue, as it will just skip the database creation if the database exists already. 
Can you please check that your database user has the permission to create tables in the database?

**Comment by Tepsiya** [comment]
the user is the correct one I used to setup the DB.. see below issue 
![solidinvoice3](https://user-images.githubusercontent.com/25186716/69605165-b5e5fa80-101f-11ea-9e2f-2ed6628f3c1d.JPG)

**Comment by Tepsiya** [comment]
is it possible to create tables and content via script and will SolidInvoice skip this step then?

**Comment by Tepsiya** [comment]
any news on this ?

**Comment by pierredup** [comment]
This should now be fixed with the latest changes in the master branch
