### ISSUE TITLE
Problem with item price value

### ISSUE THREAD

**Issue by pkoniecz** [SolidInvoice/SolidInvoice#293]
Hi, 

I installed solidinvoice ver. 2.0.3 (but in footer is still 2.0.3) from DockerHub. After short testing I noticed one problem, that when you set value of invoice item (i didn't check quotation one) less then 1 (eq. 0,65) then price is saved to DB as 0.

In the meantime I check DB structure and noticed that all fields in DB connected to item amount are defined as INT - is it ok ? Shouldn't be DOUBLE as QTY is ?

Second, I change amount fields to DOUBLE as in invoice items as weel in invoice table, Preliminary it was saved correctly, but after reediting invoice, fields have been changed to 0 value.
Is it possible to corect this functionality ?

BR

**Comment by fd6130** [comment]
I see they have convertion helper method in "MoneyBundle", so that's why they save it in integer.

**Comment by pierredup** [comment]
This is fixed in #980 and will be included in the 2.2.6 release
