### ISSUE TITLE
Add a guide on "How to install solid invoice on localhost"

### ISSUE THREAD

**Issue by kinan53** [SolidInvoice/SolidInvoice#294]
I saw this Project and this is very useful ! but the problem is that there is no guide anywhere which contains detailed instructions  of **How to install this on a localhost or on XAMPP** !
that would be fantastic if someone can help me regarding this ! i see potential in this project.... please make it worth of your hard-work guys ! thanks !

**Comment by pierredup** [comment]
@kinan53 Thank you for your interest in this project :)

Installing on localhost works pretty much the same as any other environment. You can download the latest release from https://github.com/SolidInvoice/SolidInvoice/releases (download the zip file with the name `SolidInvoice-x.x.x.zip` with `x.x.x` being the version number you want to download), extract it to a directory on your local machine, and follow the instructions at http://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html to configure Xampp (or any other local webserver you are using).

If you run into any specific issues, or if something is unclear, please let me know.

**Comment by kinan53** [comment]
ok i will try it ...

**Comment by pierredup** [comment]
If there is any additional info required, or the instructions in the docs doesn't work, then please feel free to re-open this issue and add more information.
