### ISSUE TITLE
Logo on reverts on settings save

### ISSUE THREAD

**Issue by meakajon** [SolidInvoice/SolidInvoice#296]
Hi,

When I first update the logo in settings. It will save an it is ok.

But then if I change any of the settings and I done include a logo it will revert the logo back to the SolidInvoices logo.

Very frustrating...

**Comment by pierredup** [comment]
Thanks for reporting this @meakajon, this has been fixed in #298

**Comment by meakajon** [comment]
Great, thanks for fixing. I did look at the Code but I am unfamiliar with the way the project is setup.

**Comment by meakajon** [comment]
I am having problems running the new version (2.0.4) I noticed that you have switched the OS to linux/arm from linux/amd64. So it has broken it for me.
