### ISSUE TITLE
How to donate translation?

### ISSUE THREAD

**Issue by elvirmuslic** [SolidInvoice/SolidInvoice#306]
What platform do you use for localization, I'd like to donate translations for my own language. i.e. Serbian/Bosnian/Croatian/Montenegrin as they are all the same and it would provide a great opportunity to all of these countries to use such an awesome tool!

**Comment by pierredup** [comment]
Hi @elvirmuslic.

Currently, we don't use any specific platform for translations. All translation files are part of the codebase.

If you want to add new translations, you need to copy the English translation files (E.G copy [src/ClientBundle/Resources/translations/messages.en.yml](https://github.com/SolidInvoice/SolidInvoice/blob/master/src/ClientBundle/Resources/translations/messages.en.yml) to src/ClientBundle/Resources/translations/messages.sr.yml), then update all the text to your local language. You can then [create a pull-request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) to this repository with your changes.

To help make the changes for the translation, you can use something like https://localise.biz/, which allows you to update the translation files and do the translations online.

**Comment by elvirmuslic** [comment]
Okay I have created a platform here: 
https://www.transifex.com/solidinvoice/solidinvoice/dashboard/

Everyone should be able to donate and change the translations I will manage 
The license is for a opensource project, with the MIT agreement.

**Comment by pierredup** [comment]
Thank you @elvirmuslic. Do you mind to please move the translations to a different user name? So that we can keep the SolidInvoice username for this projects with access for all members of this project. I can then set it up and be able to better integrate it with this project and manage the various resources under a single organization.

**Comment by elvirmuslic** [comment]
I mean, we can do that. However, I can give you all the permission from my
account and the public are already set so that anyone can add a
translation.
Just one yhing would be nice after to install it automatically into the
repository.

**Comment by pierredup** [comment]
I have set up a project at https://www.transifex.com/solidinvoice-app/solidinvoice-app/ with automatic integration with the repository and all the relevant project information. I would love to move this project to use solidinvoice/solidinvoice instead. Thank you for helping to translate this project.

**Comment by elvirmuslic** [comment]
That works too, okay, I'll go ahead then and add translations for Serbian. 

Great work there! Make sure to reference it on the readme.md.
