### ISSUE TITLE
list do not show all invoices

### ISSUE THREAD

**Issue by mrespin** [SolidInvoice/SolidInvoice#307]
Hiya,

I just installed and testing SolidInvoice. Therefore, I am not sure if this is a bug.
I created 3 invoices, of which 2 are recurring (ID 1 and 2)
When I list invoices I can see only one invoice ID 3 (even pending invoices number is 3)
however, if I type in the dress bar invoices/view/1, 2 and 3, I can see all 3 invoices.

**To Reproduce**
1. Create a new recurring invoice (any description, any quote, rest as is)
2. Click on save and send
3. List invoices

**Expected behavior**
I expect to see all invoices regardless of the status and type (recurring). 

**Screenshots**

![image](https://user-images.githubusercontent.com/32313960/80639777-62f2f200-8a5a-11ea-9a1a-d6824e62ede6.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome 
 - Version 81

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android 10
 - Browser chrome
 - Version 80

Thank you

**Comment by pierredup** [comment]
Hi @mrespin. By default, recurring and archived invoices are excluded from the list, so that it doesn't clutter the list. You can switch between active/recurring/archived invoices by clicking the relevant button on the top right of the grid

![Screenshot 2020-04-30 at 08 59 34](https://user-images.githubusercontent.com/144858/80681560-37efb900-8ac1-11ea-881b-e44d4244db67.png)

**Comment by mrespin** [comment]
Hi,
Thanks for your help.
The list is empty then:
![image](https://user-images.githubusercontent.com/32313960/80745156-c2fb9e00-8b17-11ea-9d46-12f7f69cea1c.png)

**Comment by mrespin** [comment]
Hi,
This is wonderful work.
However, if the bug is unexpected, I am providing with login details to debug the problem.
Please let me know ASAP, as the droplet is on the way to destroy. 
Therefore, do what you need to do:
host: 64 dot 227 dot 41 dot 36
secret: SolidInvoice1234
user: per screenshots
Thanks.

**Comment by pierredup** [comment]
Thank you @mrespin, I had a look and can confirm that the invoices does not show as expected. I will investigate the issue en provide a bug fix soon.

**Comment by Lehj14** [comment]
Hi Sir @pierredup , i would like to help on this proj you are doing to fix the bugs, I dont have a way to contact you to ask for permission so im messaging you here.

**Comment by pierredup** [comment]
Hi, @Lehj14. You are welcome to send a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) for any bugs that you want to fix or features you want to add.

**Comment by pierredup** [comment]
This should be resolved in the latest version. If this is still an issue, please feel free to re-open the issue.
