### ISSUE TITLE
File directory for SolidInvoice Data

### ISSUE THREAD

**Issue by elvirmuslic** [SolidInvoice/SolidInvoice#310]
It is a much needed feature that we should be able to place and save the data into a directory of our choosing for multiple reasons, using external data, backup, security. 

Also please respond on transifex.

**Comment by pierredup** [comment]
Hi @elvirmuslic. What data do you need to store in a different directory?
Currently, SolidInvoice stores all information in the database, nothing is persisted to the file system. The only information that is stored on the file system, is cache, and the configuration file.

**Comment by elvirmuslic** [comment]
Lets say I want it to an external location, a shared drive or similar.

**Comment by pierredup** [comment]
It is possible to install to a shared drive currently, as long as your webserver is set up to point to the shared drive
