### ISSUE TITLE
Ocramius or Install Error 

### ISSUE THREAD

**Issue by elvirmuslic** [SolidInvoice/SolidInvoice#311]
If you get an error similar to this one **on** `composer install` or `composer update`.
`
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/money.xxx.com/public_html/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33`

or 

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/money.xxx.com/public_html/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33`

**Comment by elvirmuslic** [comment]
This can be a common problem and will be resolved with the following command.

`composer require "ext-gd:*" --ignore-platform-reqs` 

It will autochoose the **ocramius** version for you that is compatible with most systems.

**Comment by pierredup** [comment]
> composer require "ext-gd:*" --ignore-platform-reqs
> 
> It will autochoose the ocramius version for you that is compatible with most systems.

Using `ignore-platform-reqs` is not really recommended, as you might get dependencies that are incompatible with your system. The above error will only happen of you run a `composer update` with PHP 7.4, and then run the application on a lower PHP version. Currently this application limits the PHP version to 7.3, which means you won't get any dependency that depend on PHP 7.4, but if you ignore the platfom requirements, then you might get incompatible dependencies

**Comment by elvirmuslic** [comment]
I understand, however, on my digitalocean and same as docker I couldnt
install it.
