### ISSUE TITLE
problem with nginx

### ISSUE THREAD

**Issue by esmm90** [SolidInvoice/SolidInvoice#319]
**Describe the bug**
I have installed this app on linux stage with nginx and php 7.4, after following the described proccedure (composer install, npm run build for prod) try to access from browser but it shows a 403 forbidden. In logs it shows for a  "directory index of "/path/to/the/app/solid_invoice/web/" is forbidden" 
I did a copy-paste of your model of vhost on instructions. 

Am I missing something? 

![image](https://user-images.githubusercontent.com/50113003/86634686-8e3d1480-bfa8-11ea-9eaf-51ccde5b7c23.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: W10
- Browser chrome
- Version Versión 83.0.4103.116 (Build oficial) (64 bits)

**Comment by pierredup** [comment]
@esmm90 Did you use the config at https://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html#configuring-nginx? And did you update the paths to match what you have on your machine?

Can you please copy your Nginx config here, as well as the path you used to install SolidInvoice

**Comment by esmm90** [comment]
Sure! 
My vhost on nginx for this app
![image](https://user-images.githubusercontent.com/50113003/86642560-605ccd80-bfb2-11ea-9d60-56e50b8a67dd.png)

The path to the app is the default nginx directory, /usr/share/nginx/html/solid_invoice/

**Comment by pierredup** [comment]
Thanks @esmm90.

What happens when you access your local server without any sub-path? (E.G just accessing `http://192.168.20.80/` instead of `http://192.168.20.80/solid_invoice/web`).

**Comment by esmm90** [comment]
The permissions are 777 and group by nginx:nginx

**Comment by esmm90** [comment]
> Thanks @esmm90.
> 
> What happens when you access your local server without any sub-path? (E.G just accessing `http://192.168.20.80/` instead of `http://192.168.20.80/solid_invoice/web`).

That is the default nginx site, I have apps running under this type:
http://192.168.20.8/app1
http://192.168.20.8/app2
and so... 

I put this one on another vhost to avoid conflicts and to do exactly like doc says

**Comment by pierredup** [comment]
> That is the default nginx site, I have apps running under this type:

The Nginx config you have shared is set up to act as a default config. So it most probably interferes with your other configs.

There are 2 options that you can try:

## 1. Use a domain alias for your VHost

This will allow you to use a custom test domain for your SolidInvoice instance.
**Note** the domain you want to use must point to your local web server.
So if you want to use `solidinvoice.localhost` for example, you need to set the `server_name` of your Nginx config to your domain

```conf
server {
    listen 80;
    server_name solidinvoice.localhost;

    # Include the rest of the config here
}
```

Then you need to add the domain to the file `/etc/hosts`. This allows your computer to use the domain as a local alias, and not look it up on the internet.

```
192.168.20.8 solidinvoice.localhost
```

(**Note:**: If your local IP address changes to something other than `192.168.20.8`, you need to update your `/etc/hosts` file to use the new IP address)

## 2. Set up Nginx config to use a sub path

If you don't want to use different local domain names for your apps and prefer to use sub-paths, then you can try the below Nginx config, which should allow you to access SolidInvoice in a sub-path without any other changes (**Note:** This config is untested, so let me know if it doesn't work out of the box)

```conf
    location ~ ^/solid_invoice {
        root /usr/share/nginx/html/solid_invoice/web;
    }

    location /solid_invoice {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }

    location ~ ^/solid_invoice/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
```

This should allow you to run SolidInvoice in a sub-path, and you can access it using `http://192.168.20.8/solid_invoice`

I would recommend using the first option, as it makes the config easier and you can access your different apps using different local domain names. Trying to run multiple apps on the same address using sub-paths can get very complicated quickly with the paths config and might cause errors in some apps or they might not work at all.
