### ISSUE TITLE
docker "exec format error" with docker tag 2.0.4

### ISSUE THREAD

**Issue by CookieCr2nk** [SolidInvoice/SolidInvoice#325]
**Describe the bug**

**To Reproduce**

Error Message from command "docker-compose logs -f" after docker-compose up -d

`solidinvoice_1  | standard_init_linux.go:211: exec user process caused "exec format error"`

**Screenshots**

**Server (please complete the following information):**
- OS: Debian 10
- Docker: 19.03.12

**Docker-Compose File**
`version: "3.6"

services:
  solidinvoice:
    image: solidinvoice/solidinvoice:2.0.4
    restart: always
    networks:
     - mariadb-cluster
     - traefik-web
    volumes:
     - "./data:/opt/srv"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.invoiceplane.rule=Host(`billling.example.com`)"
     - "traefik.http.routers.invoiceplane.entrypoints=https"
     - "traefik.http.routers.invoiceplane.tls.certresolver=cloudflare"
     - "traefik.http.services.invoiceplane.loadbalancer.server.port=80"
     - "traefik.http.middlewares.invoiceplane-compress.compress=true"
     - "traefik.http.routers.invoiceplane.middlewares=invoiceplane-compress@docker"
     - "traefik.http.middlewares.invoiceplane-ratelimit.ratelimit.average=100"
     - "traefik.http.middlewares.invoiceplane-ratelimit.ratelimit.burst=50"
     - "traefik.http.routers.invoiceplane.middlewares=invoiceplane-ratelimit@docker"

networks:
  traefik-web:
    external: true
  mariadb-cluster:
    external: true`

**Comment by Janl1** [comment]
When will we get an amd64 image version of 2.0.4?

**Comment by CookieCr2nk** [comment]
@Janl1 On which architechtures is this image working?

**Comment by Janl1** [comment]
@CookieCr2nk If you take a look at the current releases at [DockerHub](https://hub.docker.com/r/solidinvoice/solidinvoice/tags?page=1&ordering=last_updated) you will see that the tag latest is build for arm architecture which is for Rapsberry Pi and similar devices

**Comment by CookieCr2nk** [comment]
Okey thanks, so i can use it on my Raspberry PI as a Workarround.

**Comment by pierredup** [comment]
Sorry for the delay, I just pushed an updated image on Docker for linux/amd64.
You can just pull the latest `solidinvoice/solidinvoice:2.0.4` tag.
If you still want to run SolidInvoice on arm-based devices, then you can use the `solidinvoice/solidinvoice:2.0.4-arm` tag
