### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by Ghost173** [SolidInvoice/SolidInvoice#326]
i download from the git then 

$ git clone https://github.com/SolidInvoice/SolidInvoice.git
Then go into the repository directory

$ cd SolidInvoice
Now you need to get composer

$ curl -s http://getcomposer.org/installer | php
When composer is finished downloading, you can install the required dependencies:

$ php composer.phar install
After all the dependencies has been installed, the next step is to install all the web assets

$ php bin/console assets:install --symlink web
The final step is to install the Node packages, and compile all the assets

$ npm install
$ ./node_modules/.bin/gulp

then i navigate to http://www.yourdomain.com/ 
then i got this error 

An exception has been thrown during the rendering of a template ("Asset manifest file "/var/www/html/SolidInvoice/web/static/manifest.json" does not exist.").

![bugs](https://user-images.githubusercontent.com/30997116/90669006-91e1dd80-e26e-11ea-977d-5f9107ec83e6.png)

**Comment by pierredup** [comment]
The readme is not yet updated for the next version. Can you please run `npm run build`? That should fix the error

**Comment by pierredup** [comment]
@Ghost173 This should already be fixed in the master branch. If you still get an error, please feel free to re-open the issue.
