### ISSUE TITLE
install solid invoice

### ISSUE THREAD

**Issue by Daggobart** [SolidInvoice/SolidInvoice#327]
I am very new to this,
I have download solid invoice and uploaded to plesk, it tells me to install composer. I downloaded composer but have no idea where even to begin to install it. I have read tutorials, they just say type whatever code, I have no idea where to type this code.
Also have the problem with the file connected to symphony (all I can remember what file it is - something about a newer version). I have tried to search where to download this file but cant find that and don't know where to type the code to download and install it.
I have tried using the wamp window to type the code but nothing happens.
Obviously I don't know what all the technical jargon means but I am trying to learn and figure it out but after 2 days of struggling, I am hoping that you can assist me.

Your assistance would be most welcome.

Regards 

Vici

**Comment by pierredup** [comment]
Hi Vici.

I think the best option would be to download and install one of the releases available at https://github.com/SolidInvoice/SolidInvoice/releases. When you download one of the zip packages, there is no need for composer or any other steps. You should just unzip on your server, and configure your webserver according to the docs.

**Comment by Daggobart** [comment]
Hi Peirre

Thank you for your reply, I did download the source code from github but it
keeps telling me I need this composer.  Also please can you tell me how
exactly to configure the webserver, meaning where do I type in the code
explained in the tutorials.  I have tried using cmd for mysql and mariadb
but nothing happens.
I am very new to this so really dont know where to type in what. Do I use
cmd, powershell, is there something on the webserver that I must use to
type in the code?

Sorry I now that I am being a pain but I don't know where to start to
navigate to type in the code on the tutorials or the docs provided.

Regards

Vici

**Comment by Daggobart** [comment]
Dear Peirre

Please may I make a suggestion?

People like me are always looking for alternate solutions but we do not
come from a tech or coding background.  Most people give up and use wix,
weeble, squared space etc. instead of continue to learn how to do this.  I
have booked marked all the solidinvoice tutorials and the github
instructions.
The github instructions differ by creating a container using docker.  I
have asked my service provider to give me the docker extension on my
hosting package.

My suggestion is that your tutorials be more detailed for people like me.
Example - download package, upload and extract, go to docker in plesk (or
ask provider to install it), very important - where to type in the code,
meaning what application on plesk or pc do they open to type in the code
(this is my problem at the moment.

I have taught myself to write one page websites using html - still need to
learn php.  I am trying to offer people who have lost their jobs and
started small businesses with covid19 a way to give them better exposure
for their products and service at a nominal rate by hosting a one page
website to start. By the same token, fix their spelling and help with a
business profile and a professional email address so that they would be
more competitive in the marketplace and taken seriously. I would be billing
monthly for this.  Most people cannot afford the fees of web designers for
even a one page website, so I want to make that a monthly payment taking
into account their financial position currently which would be more
affordable. For people with products, it would have to be more expensive
obviously as it would take more disk space and more pages but they would
also need the online billing solution for their purposes.

So I need to get this right as right now I just cannot afford something
like whmcs. I am also a loyalist and would stick with solid invoice for all
my clients. So I really need to know how to install this properly please -
short of asking you to install it for me.

Kind regards

Vici

**Comment by pierredup** [comment]
Hi Vici

Thanks for the suggestions, I agree there is some room for improvement on the documentation.
If you download one of the releases, then there is no commands that you need to run or any docker setup that you require. They are all different ways to install SolidInvoice.

If you are a developer and want to work on the code, then you would clone the repository and run the commands. If you are a technical user and manage your own infrastructure, then you can use Docker if you are familiar with it. But for most users, you simply need to download the release and upload it to your hosting server. The file you can download is located at https://github.com/SolidInvoice/SolidInvoice/releases/download/2.0.4/SolidInvoice-2.0.4.zip. If you download and extract this file, then everything is already set up and ready to use, there are no commands that you need to run.
Let me know if are experiencing any issues.

**Comment by Daggobart** [comment]
Hi Pierre

H
I have downloaded the package from the github link, uploaded to plesk and
extracted, created a solidinvoice database, then click on the folder in
plesk file manager to open in browser - I get http error 500. I used the
zip file from the github link. The tar.gz file gives me the same error.

When I type in the browser search (using chrome) the following -
https://genixinc.co.za/SolidInvoice-2.0.4/ I get the attached error message.

When I put in http://8080:80 it brings up google search for that.
http://3306 does the same thing

When I put in  http://genixinc.co.za/solidinvoice/  it says did not match
any documents.

The only other solution that I have is to give you access to my plesk
account, so you that you can see what is happening and what I am doing
wrong and then you can see what steps I am missing in the process. This may
be the short version of fixing this.

My plesk account -  username:  cwgbyoyw  password: Y?83unm4.  My IP address
is 160.119.100.67 and the port I think is 3306 (if that is the right -
meaning port number).

I do have wamp on my pc. have downloaded symfony and installed it. Not sure
what else I can do, I really would like this to work.

I don't have anything else in plesk at the moment as I have been trying to
sort this out.

I apologise for being technologically handicapped and sounding like a
complete idiot, I am actually and garden and horticulturist and landscaper.

Regards

Vici

**Comment by pierredup** [comment]
Please do not send confidential information like usernames and passwords on this thread. It is publicly visible and any person can steal your credentials. I would suggest you immediately change your plesk password.

**Comment by Daggobart** [comment]
Oh dear I am sorry, I just don/t know how else to sort this out. I will
change it.

**Comment by Daggobart** [comment]
Hi Pierre

May I email you on your pc service email?

Regards

Vici
