### ISSUE TITLE
Can not get up and running development environment

### ISSUE THREAD

**Issue by davidmpaz** [SolidInvoice/SolidInvoice#337]
Hi,

thanks for this project!

**Describe the bug**

After forking and cloning the repository can not build docker containers. In: `docker-compose up -d` i get:

```
E: Package 'libcurl3' has no installation candidate
E: Package 'libicu57' has no installation candidate
```

**To Reproduce**

Steps to reproduce the behaviour:
1. Fork the repository
2. docker-compose up -d

Containers are not built successfully

**Expected behaviour**

Containers are built and started.

**Desktop (please complete the following information):**
- OS: iOS Catalina

Please suggest on how to proceed to get this done, i would like to make some PR related to suggestions i have. For now i will only create a ticket.

Best regards,
David

**Comment by pierredup** [comment]
Fixed in #343
