### ISSUE TITLE
Allow to use uuid or other strategy for Invoice/Quote id in templates

### ISSUE THREAD

**Issue by davidmpaz** [SolidInvoice/SolidInvoice#338]
Hello,

thanks for this project. I would like to put some suggestions into considerations.

**Is your feature request related to a problem? Please describe.**

I, as user would not like to show the Invoice/Quote IDs, which are auto increments. This reveals too much data for my taste about the system and also how many Invoices do i have generated so far. I would like that to be avoid as much as possible.

**Describe the solution you'd like**

**Short term solution**: Use property uuid instead in all related templates and pdf.
**Long term solution**: Create a settings to allow to choose the strategy to use and allow others to implement those strategies and inject them with some sort of plugin mechanism.

**Describe alternatives you've considered**

Use property uuid instead in all related templates and pdf.

Best regards,
David

**Comment by pierredup** [comment]
This has been added in #1038 and will be included in the 2.3.0 release
