### ISSUE TITLE
Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by davidmpaz** [SolidInvoice/SolidInvoice#339]
Hello,

thanks for taking care of this project.

**Describe the bug**

It seems SolidInvoice is using a version with buggy behaviour of `doctrine/annotations` see https://github.com/doctrine/annotations/issues/273 this same bug is also the root cause of #326

in DocParser.php line 1002
at DocParser->Identifier()in DocParser.php line 687
at DocParser->Annotation()in DocParser.php line 663
at DocParser->Annotations()in DocParser.php line 354
at DocParser->parse('/** * @ORM\\Table(name="security_token") * @ORM\\Entity */', 'class SolidInvoice\\PaymentBundle\\Entity\\SecurityToken')in AnnotationReader.php line 405
at AnnotationReader->collectParsingMetadata(object(ReflectionClass))in AnnotationReader.php line 338
at AnnotationReader->getClassImports(object(ReflectionClass))in AnnotationReader.php line 218

**To Reproduce**
After install i tried to update invoices view files to solve #338. 
After visiting invoice route i get the layout but no invoice block rendered.
After setting `SOLIDINVOICE_DEBUG=1`, the exception is shown.

**Expected behaviour**
Changes in templates are shown without dependencies problems

**Desktop (please complete the following information):**
- OS: ubuntu 18.04
- php 7.4

**Additional context**
Changes are only aesthetics. I am  not changing any important functionality, only displaying other variables in templates in titles and headers.

thanks in advance and best regards,
David

**Comment by pierredup** [comment]
Thanks, @davidmpaz, but this should already be fixed in the master branch. Which branch are you using when you get this error?

**Comment by davidmpaz** [comment]
Hi, thanks for answering. I was using the release tag v2.0.4. I will try `master` today evening. I will provide feedback  then.

**Comment by davidmpaz** [comment]
Hi, you were right. I clone the master branch and the problems is gone. More likely that the linked issue in this thread can be closed also.

Thanks
Best regards,
David
