### ISSUE TITLE
Fa Icons Missing

### ISSUE THREAD

**Issue by bluebridgetechnology** [SolidInvoice/SolidInvoice#357]
Hi Everyone, thanks for the amazing work done on this script.
I just installed it for the first time and noticed that all the fa-icons arent showing. I have reuploaded the font files and css files but its still the same.

![Settings](https://user-images.githubusercontent.com/33387790/102106949-d86cd080-3e39-11eb-85da-4ece3a63b821.png)

**Comment by pierredup** [comment]
Hi @bluebridgetechnology. Thank you for the report.

It looks like there might be a rewrite rule missing in the `.htaccess` file.

Can you please update your WebServer directory to use the `web` folder instead of the root directory?

**Comment by bluebridgetechnology** [comment]
Hi,
thanks for your response.
This is the .htaccess codes

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^css(.*)$ web/css/$1 [L]
    RewriteRule ^images(.*)$ web/images/$1 [L]
    RewriteRule ^js(.*)$ web/js/$1 [L]
    RewriteRule ^uploads(.*)$ web/uploads/$1 [L]
    RewriteRule ^bundles(.*)$ web/bundles/$1 [L]
    RewriteRule ^swf(.*)$ web/swf/$1 [L]
    RewriteRule ^(.*)$ web/app.php [QSA,L]
</IfModule>

the rewrite engine is on but still it seems most assets in the web folder are not being interpreted.

**Comment by bluebridgetechnology** [comment]
Okay so in the installation I had to specifiy the "web" directory and all the icons were showing,but when you get to the config page its all messed up an nothing is selectable

**Comment by pierredup** [comment]
Do you mind pasting a screenshot of what it looks like?

**Comment by peternagelsa** [comment]
> Okay so in the installation I had to specifiy the "web" directory and all the icons were showing,but when you get to the config page its all messed up an nothing is selectable

Where precisely do you specify the "web" directory please?

**Comment by peternagelsa** [comment]
> Hi @bluebridgetechnology. Thank you for the report.
> 
> It looks like there might be a rewrite rule missing in the `.htaccess` file.
> 
> Can you please update your WebServer directory to use the `web` folder instead of the root directory?

Please clarify how do I update the webserver directory to use the web folder and not the root directory. Fa icons not showing as well as payment gateways, I assume most assests will not show?

**Comment by pierredup** [comment]
@peternagelsa Please have a look at the webserver configuration at https://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html. If you use Apache or Nginx, then you can follow the recommended config on that page

**Comment by peternagelsa** [comment]
> @peternagelsa Please have a look at the webserver configuration at https://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html. If you use Apache or Nginx, then you can follow the recommended config on that page

Thanks Pierre for the swift reply. It is appreciated!

**Comment by peternagelsa** [comment]
Pierre 

May I 'bug' you again please. I am setting this up for a friend of mine, but he has a domain on shared hosting. I installed the software on a subdomain. Is there any other way to point the system to use /web and not /root if I cannot set up a custom virtual host?

Thanks in advance

**Comment by pierredup** [comment]
@peternagelsa On shared hosting, it's a bit tricky to use the `web` folder.
In the upcoming version 2.1, this has been improved quite a bit to make some of the rewrites easier, but for the current stable version, it takes some extra effort.

I'm going to make a few assumptions here, and try to explain it best I can base on the assumptions (if any of them is incorrect, please feel free to correct me).

I'm going to assume your shared hosting provider is using **cPanel** with Apache and standard PHP setup.
Let's say that the username of the account is **`myusername`** (replace this with the username of your hosting server).
Let's also assume that you want to set up SolidInvoice on a subdomain called **billing.example.com**.

This setup might differ between hosting providers, so I'm assuming the default functionality of cPanel here.

When setting up a sub-domain, you have the option to specify the document root directory:

![Screenshot 2021-02-03 at 23 40 59](https://user-images.githubusercontent.com/144858/106813276-71b9a580-6679-11eb-9ad3-b71bc9c1ec5a.png)

Using this config will create a directory called `billing.example.com` in the `public_html` directory.

This is where you would specify the `web` directory as the document root. So creating the sub-domain should look something like this:

![Screenshot 2021-02-03 at 23 43 41](https://user-images.githubusercontent.com/144858/106813477-b7766e00-6679-11eb-8c9b-d812e8c33a58.png)

Now you can upload SolidInvoice to the `/home/myusername/public_html/billing.example.com` directory.
You can overwrite the `web` directory that was created when creating the sub-domain when uploading the files.

This should then allow you to use the `web` directory as the document root while keeping all the files in a separate directory for the sub-domain outside of the document root.

I hope this helps (I know the documentation needs a lot of work, I'll try and add these steps to the docs when releasing 2.1)

**Comment by peternagelsa** [comment]
> @peternagelsa On shared hosting, it's a bit tricky to use the `web` folder.
> In the upcoming version 2.1, this has been improved quite a bit to make some of the rewrites easier, but for the current stable version, it takes some extra effort.
> 
> I'm going to make a few assumptions here, and try to explain it best I can base on the assumptions (if any of them is incorrect, please feel free to correct me).
> 
> I'm going to assume your shared hosting provider is using **cPanel** with Apache and standard PHP setup.
> Let's say that the username of the account is **`myusername`** (replace this with the username of your hosting server).
> Let's also assume that you want to set up SolidInvoice on a subdomain called **billing.example.com**.
> 
> This setup might differ between hosting providers, so I'm assuming the default functionality of cPanel here.
> 
> When setting up a sub-domain, you have the option to specify the document root directory:
> 
> ![Screenshot 2021-02-03 at 23 40 59](https://user-images.githubusercontent.com/144858/106813276-71b9a580-6679-11eb-9ad3-b71bc9c1ec5a.png)
> 
> Using this config will create a directory called `billing.example.com` in the `public_html` directory.
> 
> This is where you would specify the `web` directory as the document root. So creating the sub-domain should look something like this:
> 
> ![Screenshot 2021-02-03 at 23 43 41](https://user-images.githubusercontent.com/144858/106813477-b7766e00-6679-11eb-8c9b-d812e8c33a58.png)
> 
> Now you can upload SolidInvoice to the `/home/myusername/public_html/billing.example.com` directory.
> You can overwrite the `web` directory that was created when creating the sub-domain when uploading the files.
> 
> This should then allow you to use the `web` directory as the document root while keeping all the files in a separate directory for the sub-domain outside of the document root.
> 
> I hope this helps (I know the documentation needs a lot of work, I'll try and add these steps to the docs when releasing 2.1)

Hi Pierre, I genuinely appreciate this. Your assumptions were all spot on and SolidInvoice runs like a charm.

**Comment by pierredup** [comment]
I'm closing here, as I think the issues should be sorted. Feel free to re-open if there are any other issues.

**Comment by peternagelsa** [comment]
Hi Pierre 

 

Just wondering when you plan to release 2.1 of Solid Invoice? I downloaded the latest code but it fails to initiate the install (error 500). 

 

Thanks in advance

Peter

 

Business WhatsApp 067 906 1931

Communication Platform  <https://digitalhub.capetown/> https://digitalhub.capetown 

Virtual Office Space  <https://digitalhub.africa/> https://digitalhub.africa 

eMail  <mailto:billing@fusionhub.co> billing@fusionhub.co |  <mailto:support@fusionhub.co> support@fusionhub.co |  <mailto:helpdesk@fusionhub.co> helpdesk@fusionhub.co 

Fusion Hub Website  –  <https://www.fusionhub.co/> https://www.fusionhub.co  

Fusion Hub Services –  <https://www.fusionhub.services/> https://www.fusionhub.services 

 



 

This message may contain Fusion Hub (Pty) Ltd’s confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. The information transmitted in electronic mail does not necessarily represent the views of Fusion Hub (Pty) Ltd. E-mail transmission cannot be guaranteed to be secured or error-free as information could be intercepted, corrupted, lost, destroyed, received late or incomplete, or could contain viruses. The sender therefore does not accept liability for any error or omission in the contents of this message, which arises as a result of e-mail transmission.  No representation is made that this email or any attachments are free of viruses. Virus scanning is recommended and is the responsibility of the recipient.

**Comment by pierredup** [comment]
@peternagelsa I still need to re-work the notifications and fix a couple of small bugs then 2.1 should be ready. Currently, I can't give a timeline but hoping to get to it very soon.
