### ISSUE TITLE
demo throws 401 when trying to create a customer

### ISSUE THREAD

**Issue by parijke** [SolidInvoice/SolidInvoice#364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lehj14** [comment]
Hi @pierredup , I want to contribute and help but when i try to use docker and config db I get 500 Internal Server Error

The following error occurred:

An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

Any help on setting my dev?

**Comment by pierredup** [comment]
@Lehj14 Can you please open a new issue, so that we can track and work on it separately from this reported issue? Thanks.

**Comment by pierredup** [comment]
This has been resolved on the demo.
