### ISSUE TITLE
Payment Bug

### ISSUE THREAD

**Issue by OverboredThekid** [SolidInvoice/SolidInvoice#365]
Describe the bug:
After sending out a payment invoice to a client and selected to pay it sends the client to a different page stating they have paid without going to the respective payment portal

To Reproduce
go to 'invoices'
then 'create invoice'
select any user and for any amount
Click 'save and send'
next click 'send' (don't know if this is another bug but you must press again)
Open invoice email and click the 'Pay Now' button
select one of the following "Stripe Checkout", "Paypal express checkout" or "Stripe js" on Payment method
leave amount the same
Click 'Pay Now'
then redirects to a page stating "Payment Has Been Completed" without opening the respective portals
See error:

Expected behavior:
When 'Pay Now' pressed takes the user to a pay portal

Desktop (please complete the following information):
Device: PC
OS: Windows 10
Browser: chrome
Version: 89.0.4389.82

Smartphone (please complete the following information): iPhone XR
OS: 14.4
Browser chrome, safari
Version  89.0.4389.82 , 14.0

Additional context:

**Comment by OverboredThekid** [comment]
I updated the format, sorry for not doing it in the first place. hoping this gets fixed soon, we really like this program! hope to hear back from support soon! :D

**Comment by pierredup** [comment]
@OverboredThekid Thanks for the report. I'm busy looking into this but need a bit more info, please.

* What version of SolidInvoice are you using?
* What payment gateway are you using?
* Are you experiencing this issue with specific payment gateways or all of them>

**Comment by OverboredThekid** [comment]
Thank you, 

I’m using version 2.0.4

Stripe, and paypal (both checkouts)

I only have a PayPal and stripe account and both methods are having the same issue

**Comment by pierredup** [comment]
Thanks for the feedback @OverboredThekid. I'll see if I can replicate it and provide a fix

**Comment by OverboredThekid** [comment]
If it would help at all I can send in a video or give you access to the files. I'm still having the same issue

**Comment by OverboredThekid** [comment]
Hello, I’m just seeing if there has been any update or progress on my issue??

**Comment by SelfSufficient08** [comment]
I have the same exact issue.  Trying to use Stripe.  Awesome product and am hoping this gets resolved.

**Comment by OverboredThekid** [comment]
Hey, I'm just wondering if there has been any update on this problem?

**Comment by pierredup** [comment]
@OverboredThekid Sorry for the delay. I managed to find the issue and I'm busy working on a fix in #400 (along with some other issues around payments that I picked up while testing).
This issue will only be fixed in the 2.1 release, which should be released within the next month.
