### ISSUE TITLE
Install on localhost Error 

### ISSUE THREAD

**Issue by JamirHossainAfridi** [SolidInvoice/SolidInvoice#373]
i am following https://docs.solidinvoice.co/en/latest/guide/getting_started/webserver.html#configuring-apache to install SolidInvoice on my localhost. But when i run php bin/console server : run i get 

In ExposedRoutesExtractor.php line 259:
  Type error: implode(): Argument #2 ($array) must be of type ?array, string given
how can i fixed it.
php version : 8.0.3
SolidInvoice version : 2.0.4

**Comment by pierredup** [comment]
@JamirHossainAfridi SolidInvoice version 2.0.4 is not compatible with PHP 8. Only the upcoming 2.1 version is compatible with PHP 8 (current 2.x branch). You can either use PHP 7.4, or try using the `2.x` branch.

**Comment by JamirHossainAfridi** [comment]
i have tried with php version 7.4.16 and got  "There are no commands defined in the "server" namespace" error.
