### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by Blejzer** [SolidInvoice/SolidInvoice#383]
**Describe the bug**
Demo at demo.solidinvoice.co is not working. Cannot get logged it. Get the following error
"The following error occurred:
Bad credentials."

**To Reproduce**
1. Go to 'https://demo.solidinvoice.co/'
2. Click on 'Login'

**Expected behavior**
Show next page

**Comment by pierredup** [comment]
Thanks, @Blejzer, the demo is working again now.
