### ISSUE TITLE
Run app

### ISSUE THREAD

**Issue by spiritua** [SolidInvoice/SolidInvoice#388]
npm run build and npm run server
 
not found
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC\AppData\Local\npm-cache\_logs\2021-06-22T03_29_33_823Z-debug.log

**Comment by spiritua** [comment]
i have many problem for installation, please can you help me?

**Comment by pierredup** [comment]
Please test using the latest version. The best way to install is to download the archive from the release page and extracting it to a folder. Running NPM commands should only be necessary when cloning the repository when trying to contribute to the project.
