### ISSUE TITLE
[QUESTION] How / Where can you change the base url?

### ISSUE THREAD

**Issue by bmcgonag** [SolidInvoice/SolidInvoice#390]
After running this with Docker-compose the first time, I noticed thta the base URL seemed to affect how the system works from a routing perspective.  

I want to make my system run through a reverse proxy now, but know I need to change the base url, but can't seem to find where to change it. 

Any help is greatly appreciated.  this looks like a tremendous app.

**Comment by pierredup** [comment]
This should be resolved in the latest version, since we don't use a Base URL anymore. If you still experience any issues, please feel free to re-open this issue and provide more details.
