### ISSUE TITLE
Missing first letter from client address

### ISSUE THREAD

**Issue by lonesomewalker** [SolidInvoice/SolidInvoice#394]
**Describe the bug**
Client address is missing the first letter on quote, and also print/pdf version.

**To Reproduce**
add a new client, create new quote, fill all fields for the client.

**Expected behavior**
Should show every line as saved in database (yes, it is saved correctly), and not cutting of first letter/replace it by space.

**version**
2.0.4

**Comment by pierredup** [comment]
@lonesomewalker I was unable to reproduce this on the latest 2.1.0 release. If this is still an issue, please let me know, and please include a screenshot of the issue.

**Comment by pierredup** [comment]
Closing this as I'm not able to reproduce it. If this is still an issue, please re-open this and include some screenshots or any additional information.
