### ISSUE TITLE
Issues with Content over http

### ISSUE THREAD

**Issue by mrchainman** [SolidInvoice/SolidInvoice#396]
**Describe the bug**
I am using the Dockerimage and am running it behind the nginx proxy manager.
On all other services, I can just leave http as the backend connection and it works.
With Solidinvoice, I get warned about content being loaded over http.
I don't know how big of a deal it is, but since on the demo version of Solidinvoice I don't get any warnings something must be configured wrong.

**To Reproduce**
Create a docker-compose file with nginx proxy manager and solidinvoice and bring the project up.
Configure the proxy host in nginx proxy manager to connect to the service name wia http, but request the ssl certificate.

**Expected behavior**
Altough the backend is http, the connection should be secre.

**Screenshots**
![Screenshot_20210829](https://user-images.githubusercontent.com/59087991/133823284-e3f99499-9c55-4bfd-872f-8339ffc8e457.png)

**Desktop (please complete the following information):**
- OS: Linux thinkpad 5.14.2-zen1-2-zen #1 ZEN SMP PREEMPT Thu, 09 Sep 2021 09:42:32 +0000 x86_64 GNU/Linux
- Browser: Ungoogled Chromium
- Version: Version 92.0.4515.131 (Official Build, ungoogled-chromium) Arch Linux (64-Bit)

Additional notes:
The logs don't show anything useful, but on request I can provide whatever is needed.

**Comment by julianobst** [comment]
@mrchainman did you change the protocol from http to https of the base URL during the installation?
![image](https://user-images.githubusercontent.com/12269611/176720672-d3f94316-76e2-4658-b295-5614920f3054.png)

After I changed this, the application worked correctly for me.

Greetings,
Julian

**Comment by pierredup** [comment]
This should be resolved in the latest version, since we don't use a Base URL anymore. If this problem still persists, please feel free to re-open this issue and provide more details.
