### ISSUE TITLE
Solidinvoice using docker image

### ISSUE THREAD

**Issue by ghost** [SolidInvoice/SolidInvoice#397]
**Describe the bug**

**To Reproduce**
1. Setup 
2. run mysql server
3. click next in the ui

**Expected behavior**
I'm trying to install solidinvoice using provided docker images and i'm getting a mysql linking error.

**Screenshots**
If applicable, add screenshots 
![image (4)](https://user-images.githubusercontent.com/25317204/143170522-e9021042-e3f3-4a90-9fec-2851b3b2fad4.png)

explain your problem.

**Desktop (please complete the following information):**
- OS: ubuntu
- Browser chrome
- Version latest

**Comment by shakeebshaan** [comment]
what is the solution to this

**Comment by UnknownArti** [comment]
Only solution that I found is to allow external connections to your mysql server and then set the mysql user to  docker's internal address, which for me is 'solidinvoice'@'172.0.0.1', you'll also have to specify your external IP as the hostname for the mysql database.

**Comment by bmcgonag** [comment]
You can alternatively run mysql container / mariadb container inside the same docker-compose file with solid invoice.  That's what I did.  I just setup both as containers.

**Comment by pierredup** [comment]
New docker images have been published for the latest version of SolidInvoice. If there are still any issues, please feel free to open a new issue.
