### ISSUE TITLE
Latest Docker image 2.1.0 point to the old 2.0.4 version

### ISSUE THREAD

**Issue by mariushosting** [SolidInvoice/SolidInvoice#432]
Latest Docker image 2.1.0 points to the old 2.0.4 version image
@pierredup

**Comment by pierredup** [comment]
@mariushosting I haven't built and pushed any new docker images yet for the new release. I'll try and get to it within this week

**Comment by mariushosting** [comment]
Thank you so much for the effort!

**Comment by pierredup** [comment]
@mariushosting I have pushed docker images for version 2.1.0, and have also updated the `latest` tag to 2.1.0

**Comment by mariushosting** [comment]
Unfortunately I can't get it working. The server returned a "500 Internal Server Error" after add the correct Database Config. No error in the previous 2.0.4 version.

**Comment by mariushosting** [comment]
![server error](https://user-images.githubusercontent.com/37554361/191913810-b1dec314-bc54-4e22-86b3-38ecb98a003f.png)
@pierredup
