### ISSUE TITLE
Multi-tentant

### ISSUE THREAD

**Issue by zerorail** [SolidInvoice/SolidInvoice#447]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pierredup** [comment]
@sparkmobi Can you please update the description with your question/query/suggestion? Based on the title, I'm not sure exactly what this issue is about or what you are requesting.

**Comment by pierredup** [comment]
The latest version (2.2) includes support for multiple companies. This should address this issue, but if there are any additional feature requests around multi-tenancy, please feel free to re-open this and add more details.
