### ISSUE TITLE
Docker 500 Internal Server Error

### ISSUE THREAD

**Issue by mariushosting** [SolidInvoice/SolidInvoice#459]
Docker Release 2.1.0 is bugged

As explained here> https://github.com/SolidInvoice/SolidInvoice/issues/432

Every time you try to install it
Returned a "500 Internal Server Error" after add the correct Database Config. No error in the previous 2.0.4 version.
![191913810-b1dec314-bc54-4e22-86b3-38ecb98a003f](https://user-images.githubusercontent.com/37554361/192367425-650bbb6c-54da-42b0-8f02-c063467f2cb9.png)

@pierredup

**Comment by pierredup** [comment]
@mariushosting @rongkn Can you please try again with the latest docker image? (or version 2.1.1)

**Comment by mariushosting** [comment]
@pierredup Now it's working! Only the name at the top of the page (TAB) is not correctly set up when creating the database :-)
![afScreenshot 2022-09-27 16 23 14](https://user-images.githubusercontent.com/37554361/192539776-0e59f0b8-e445-439a-89a5-83f2e10a1fcf.png)

**Comment by mariushosting** [comment]
And something unrelated to the issue: the email in the dashboard is not properly centered and changing themes under system settings is not working.
![not relatedUntitled8](https://user-images.githubusercontent.com/37554361/192544191-2551cb11-0d97-462f-8673-3afa92330b85.png)

Hope this helps! I love SolidInvoice!

**Comment by pierredup** [comment]
Thanks for the feedback @mariushosting! I have created PRs (#463 and #464) to address the issues you mentioned.

**Comment by rongkn** [comment]
> 



> 

@mariushosting  @pierredup still have a issue with 2.1.1.-dev get the following error when try and pay now , only credit works all the other fail with  Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I have been pretty much unable to use the application to do anything have tried to redo with the latest docker image  

Log in screen is huge 
I will attach the screenshots 
![logon screen ](https://user-images.githubusercontent.com/32495778/198098518-357fe312-9b43-4de6-bbc3-05bd750750e3.JPG)
![Bank transfer for payment](https://user-images.githubusercontent.com/32495778/198098546-63d56e3a-2dad-4e50-bc0d-3160b61075a7.JPG)
![Bank transfer for payment error](https://user-images.githubusercontent.com/32495778/198098552-6437f7da-e017-41c0-84fb-ae866d2d3147.JPG)
