### ISSUE TITLE
Asset manifest file does not exist

### ISSUE THREAD

**Issue by deloptes** [SolidInvoice/SolidInvoice#660]
**Describe the bug**

**To Reproduce**

1. git clone
2. composer install
3. call UI in web browser

**Expected behavior**

**Screenshots**
An exception has been thrown during the rendering of a template ("Asset manifest file "/var/www/SolidInvoice/public/static/manifest.json" does not exist. Did you forget to build the assets with npm or yarn?").

**Desktop (please complete the following information):**
- OS: Linux
- Browser: Firefox
- Version: 101

**Additional context**
I also tried the ZIP, there it was having trouble with passing the password to the DB.
I am wondering, are you able to produce something working? If yes, please let me know which version exactly is working and write down usable Howto.

Also I noticed something in the Howto provided mentioning npm - this is no go on production server - it pulls a bunch of dev packages.

*Short summary*
Disappointed

**Comment by Technetium1** [comment]
Run in Docker if you need everything isolated on production server. Choose a better issue name.

**Comment by deloptes** [comment]
No need - will not use this product and do not need to change the name - it says everything.
Fix on your end and please, do not tell me what to use or what to do.

BR

**Comment by deloptes** [comment]
Ready to compromise, I hope you too - let me know, which version works according installation notes. Please post links to both.
Thank you

**Comment by Technetium1** [comment]
I'm just someone following the repo and commenting on the issue. I'm not fixing anything anywhere. Here's a link on how to run this, from start to end: https://hub.docker.com/r/solidinvoice/solidinvoice/

**Comment by pierredup** [comment]
@deloptes When cloning the repository, you need to install the node dependencies and run the build script to generate the assets. If you are concerned about the node modules on the server, then you can just delete the files after generating the assets

```bash
yarn install
yarn build
rm -Rf node_modules
```

The best way to setup for a production server, is downloading the zip from the release. It has the assets pre-compiled in the archive along with the vendor dependencies, so there are no additional steps required.
If this doesn't work for you, then please create a new issue with details about the error you are getting.

**Comment by deloptes** [comment]
> The best way to setup for a production server, is downloading the zip from the release. It has the assets pre-compiled in the archive along with the vendor dependencies, so there are no additional steps required. If this doesn't work for you, then please create a new issue with details about the error you are getting.

thank you, the ZIP did not work either. I won't spent time creating issues.

**Comment by pierredup** [comment]
> the ZIP did not work either. I won't spent time creating issues

That is unfortunate, because I can't improve the application and fix issues if I don't know what the errors are.

**Comment by deloptes** [comment]
> > the ZIP did not work either. I won't spent time creating issues
> 
> That is unfortunate, because I can't improve the application and fix issues if I don't know what the errors are.

you could produce at least installation notes that work

**Comment by pierredup** [comment]
> you could produce at least installation notes that work

That is what https://docs.solidinvoice.co/en/latest/guide/getting_started.html is for, and if there are errors, that is what the issue tracker are for.
