### ISSUE TITLE
Edit Created Date of Invoice

### ISSUE THREAD

**Issue by phybersplice** [SolidInvoice/SolidInvoice#682]
**Is your feature request related to a problem? Please describe.**
The ability to edit the created date of an invoice in order to backdate it.

**Describe the solution you'd like**
A "pencil" to edit the date somewhere in the GUI.

**Describe alternatives you've considered**
Otherwise I'd have to go into the DB to edit it.

**Additional context**

**Comment by pierredup** [comment]
@phybersplice I'm not sure if the created date should be editable, since it's a timestamp of when the invoice was generated. What is the use case of wanting to backdate an invoice? Do you think a different field will solve your use case, E.G a custom due date?

**Comment by phybersplice** [comment]
Hi

Simply put, I need to enter previous invoices from an excel sheet that have already been paid with specific dates.  I can’t use current dates.  
it messes up the accounting if 15 invoices use today’s date of entry when printing the invoice.

**Comment by pierredup** [comment]
Thanks for the feedback, I'll add this as a feature request for an upcoming version

**Comment by jinxlal** [comment]
Another upvote for this feature request!
