### ISSUE TITLE
List Invoice Screen Has Overlap Between Client Name and Amount Owing

### ISSUE THREAD

**Issue by phybersplice** [SolidInvoice/SolidInvoice#715]
**Describe the bug**
When Chrome is at 100% zoom, the Client name (if it's a long name) and the amount owing overlaps as showing in the screenshot.

**To Reproduce**
Reducing the zoom to an appropriate size prevents the overlap.

**Expected behavior**
A word wrap would be best to accomodate the overlap.

**Screenshots**
![Overlap](https://user-images.githubusercontent.com/3407554/229003290-358ba5ed-4342-4532-821c-d4787c7869f7.jpg)

**Comment by pierredup** [comment]
@phybersplice Thanks for the report, it is fixed in https://github.com/SolidInvoice/SolidInvoice/commit/22c955b08c29f4f34d4c1e39bd0959767e1f82b9 and will be released with version 2.2.1
