### ISSUE TITLE
Upgraded to 2.2.2 and the invoices show payment method as currency

### ISSUE THREAD

**Issue by phybersplice** [SolidInvoice/SolidInvoice#802]
Upgraded to 2.2.2 and the invoices show payment method as currency.

@pierredup
I upgraded to 2.2.2 and the issue remains.  
The previous invoices show currency, not payment method.

_Originally posted by @phybersplice in https://github.com/SolidInvoice/SolidInvoice/issues/784#issuecomment-1537151505_

**Comment by pierredup** [comment]
@phybersplice Can you please attach a screenshot of the issue? Thanks.

**Comment by phybersplice** [comment]
Here you go:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/3407554/236630431-74288d37-2167-4547-852e-1841905f0356.png">

**Comment by pierredup** [comment]
This has been fixed in #843 and will be included in the 2.2.4 release.
