### ISSUE TITLE
Reporting 3 Bugs !

### ISSUE THREAD

**Issue by hedho** [SolidInvoice/SolidInvoice#833]
**Describe the bug**
1. The drop down menu under actions doesn't show up.
2. Can't Delete invoices !
3. Payment through Credit or cash or any give error output: "500 Internal Server Error"

**To Reproduce**
1. Go to 'List Invoices'
2. Click on '... Drop down menu'
3. See error

**To Reproduce**
1. Go to 'List Invoices'
2. Click on 'Select desired invoices'
3. Click on 'Delete'
4.Click on 'OK'
5. See error 'Deletion doesn't happened!

**To Reproduce**
1. Go to 'List Invoices'
2. Click on 'Select desired invoices which is on pending'
3. Click on 'Pay now'
4. Click on 'Payment Method / chose Credit'
5. Click 'Pay Now'
5. See error 'The server returned a "500 Internal Server Error".!

The whole testing was done under latest version of 2.2.3
Installed by using `docker run --name solidinvoice -p <APP_PORT>:80 -d solidinvoice/solidinvoice:<VERSION>-full`

Search function under List invoices doesn't seem to work!
To reproduce it you simply create an invoice and search by client name the output will be "no data"

**Screenshots**
![brave_MdM0fdZuKe](https://github.com/SolidInvoice/SolidInvoice/assets/224877/0f9b833b-ee27-412e-b0d4-cc1c09f51b69)
![brave_uGySaGwb1C](https://github.com/SolidInvoice/SolidInvoice/assets/224877/fecebe8f-703f-4748-a2db-fe811d24d494)
![brave_5bLfih1Xgl](https://github.com/SolidInvoice/SolidInvoice/assets/224877/a49b1a87-23cf-4296-83cb-f80b4c22cc86)

**Comment by pierredup** [comment]
Thanks for the report @hedho.

The issues will be fixed in #836, #837 and #841 respectively and will be included in the 2.2.4 release.

**Comment by hedho** [comment]
> Thanks for the report @hedho.
> 
> 
> 
> The issues will be fixed in #836, #837 and #841 respectively and will be included in the 2.2.4 release.

Thank you for the hard work.
