### ISSUE TITLE
Online app broken: 500 Internal Server Error

### ISSUE THREAD

**Issue by SimpleXRPTools** [SolidInvoice/SolidInvoice#839]
**Describe the bug**
I was checking out the online app last week but now it seems it's 100% broken. There is now only a '500 Internal Server' Error, when going to: 
https://solidinvoice.app/dashboard

![Screenshot 2023-05-16 143740](https://github.com/SolidInvoice/SolidInvoice/assets/56190586/98b921cd-497b-4779-809d-4fbdffd81835)

**Comment by pierredup** [comment]
@SimpleXRPTools This sometimes happens when the current active company gets lost in the session. I'll have a look if I can get a proper fix in place, but as a workaround, you can go to https://solidinvoice.app/logout to log out, then log back in. That should get rid of the error.

**Comment by SimpleXRPTools** [comment]
Thanks @pierredup

Tried the logout workaround, the logout worked, but unfortunately it still has the same error after logging back in.

I also tried to login on a newly created incognito tab, using Chrome, but was met with the same error as before. Although, now the page is https://solidinvoice.app/select-company

**Comment by pierredup** [comment]
@SimpleXRPTools That error should be resolved now when going to [solidinvoice.app/select-company](https://solidinvoice.app/select-company). It was a issue with a case-sensitive filesystem on the server (fixed by [be6b336](https://github.com/SolidInvoice/SolidInvoice/commit/be6b3362450a5074b1d5a8cdbd4acebc1b1a4a32))

**Comment by SimpleXRPTools** [comment]
Thanks @pierredup 

That's all fixed and is working as normal.
