### ISSUE TITLE
Invoice Numbering

### ISSUE THREAD

**Issue by rongkn** [SolidInvoice/SolidInvoice#852]
**Describe the bug**
When I created a new invoice it completed  successfully it started the invoice at number 1  and counted  up successfully until  the tenth invoice and everything after the tenth one keep number 10 as the invoice number so now I have bunches of invoices as number 10.  Is there a fix for this 

Also can I edit the numbering of the invoice counter instead of starting at 1,  I have many old invoices in the 300 range and would like to continue with that numbering scheme. 

Best Regards 
Ronk
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rongkn** [comment]
Steps to reproduce the behavior:
When I created a new invoice it completed successfully it started the invoice at number 1 and counted up successfully until the tenth invoice and everything after the tenth one keep number 10 as the invoice number so now I have bunches of invoices as number 10. Is there a fix for this

Also can I edit the numbering of the invoice counter instead of starting at 1, I have many old invoices in the 300 range and would like to continue with that numbering scheme

Expected behavior
A clear and concise description of what you expected to happen.

I would expect the invoice number to increment each invoice instead of stopping at ten and anything after that is assigned 10 no matter how many I create. I ID numbers are all different on the invoices but it stopped incrementing the count after it reaches invoice #10 and keeps assigning 10 to everything.

Screenshots
If applicable, add screenshots to help explain your problem.
I have attached invoice numbering.jpg and invoice numbering 2 jpg
also attached payment id jpg and payment id 2 jpg

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [chrome]
Version [Version 113.0.5672.127 (Official Build) (64-bit]

![Invoice Numbering](https://github.com/SolidInvoice/SolidInvoice/assets/32495778/a2690077-278e-4954-a56c-acc352d4816a)
![Invoice Numbering 2](https://github.com/SolidInvoice/SolidInvoice/assets/32495778/bc3bbb27-39ca-4a1d-b85b-d0d45ae8adb3)
![payment id](https://github.com/SolidInvoice/SolidInvoice/assets/32495778/6c59ba57-2d10-4d84-8efa-4c33aa70170e)
![payment id 1](https://github.com/SolidInvoice/SolidInvoice/assets/32495778/2ff1e11b-69d8-4982-ad45-f4db3788834a)

**Comment by pierredup** [comment]
@rongkn Thanks for the report! This has been fixed in #853 and will be included in the 2.2.4 release.

> Also can I edit the numbering of the invoice counter instead of starting at 1, I have many old invoices in the 300 range and would like to continue with that numbering scheme.

Currently the only way to achieve this is to update the invoice number in the database. You can edit the `invoice_id` column of the last invoice in the `invoices` table to any value you want, then the next created invoice will increment from the last number. We do plan to add a custom numbering scheme in the next release, but we don't have a timeline of when this release will be ready.

**Comment by rongkn** [comment]
@pierredup can you tell me where the database is located is it the ibdata1 in the screen shot or in another level  and what is the best app to edit with 
![root](https://github.com/SolidInvoice/SolidInvoice/assets/32495778/6660ecb2-5eb8-4f06-bf3b-2578276ed490)
