### ISSUE TITLE
This value should be greater than 0 Error Message

### ISSUE THREAD

**Issue by MohamedHussain1** [SolidInvoice/SolidInvoice#870]
**Describe the bug**

When trying to apply for a payment under 1.0, for example, 0.25 I get the following message.

Error: This value should be greater than 0.

**To Reproduce**
1. Go to an unpaid invoice with the unpaid amount under 1.0
2. Click on 'Pay Now
3. Scroll down to 'Cash' in the Payment method
4. In the amount under 1.0 into the amount box
5. See an error

**Expected behavior**
Apply any amount above zero in the first tenth and hundredth.

**Comment by CherryDT** [comment]
Is this the same issue as #958 and therefore fixed too?
