### ISSUE TITLE
500 error on creating new invoice

### ISSUE THREAD

**Issue by JitteryDoodle** [SolidInvoice/SolidInvoice#898]
**Describe the bug**
I eventually start to get 500 errors on creating new invoices. This is happening both on my own docker install and _**also**_ on solidinvoice.app.

Specifically, this is the error I get:

> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**To Reproduce**
1. Set up solid invoice company
2. Set up emails through Gmail
3. Set a logo and all personal info
4. Create an invoice like normal for client
5. Wait a bit..
6. Try to create another invoice for the client
7. Get 500 error

Once the error is shown, it happens every time, so it's easily reproducible after that fact, even after logging out:
1. Log out if you're logged in
2. Log back in
3. Click create invoice
4. Get 500 error 

**Expected behavior**
I should be able to create invoices like normal, without 500 errors. Especially on SolidInvoice's own website!

**Screenshots**
Note that this is on solidinvoice.app's own website:
![2023-06-27_12-28](https://github.com/SolidInvoice/SolidInvoice/assets/22568661/a0ef4f26-974d-48a2-87c8-94adbaf1193e)

**Desktop (please complete the following information):**
- OS: Pop_OS 22.01
- Browser: Firefox Nightly
- Version: 116.0a1 (2023-06-17)

**Comment by pierredup** [comment]
This should be resolved with the latest version. If the error still happens, please feel free to re-open this issue
