### ISSUE TITLE
Individual polyfill packages should be used instead of symfony/polyfill

### ISSUE THREAD

**Issue by stof** [SolidInvoice/SolidInvoice#939]
Currently, this package depends on `symfony/polyfill` instead of the individual `symfony/polyfill-*` packages.
This package installing the whole mono-repo is discouraged as it installs much more stuff than necessary.

The Symfony team (which I'm a member of) [recommends using the individual packages](https://github.com/symfony/polyfill/tree/1.x#usage) instead. If we were starting it today, we would not even publish the `symfony/polyfill` package on Packagist at all, keeping it a development-only mono-repo.

**Comment by pierredup** [comment]
@stof Symfony should stop publishing the [symfony/polyfill](https://packagist.org/packages/symfony/polyfill) package then and mark it as abandoned in Packagist

**Comment by stof** [comment]
this is being discussed. And this is the reason why I opened this issue to make you aware.
The readme explicitly mentions (since years) the recommended setup, so you should probably still migrate.

I looked at the packagist dependents of the mono-repo package. There is only 15 such packages (when looking only at requirements and not dev requirements) and you are one of the very few of them that is still active (as is, has commits in 2023).
