### ISSUE TITLE
Cent values are ignored 

### ISSUE THREAD

**Issue by Nilson** [SolidInvoice/SolidInvoice#958]
**Describe the bug**
Cent values are ignored when creating an invoice. Thus, the total amount is less than desired.

**To Reproduce**
1. Go to https://solidinvoice.app and create an invoice with an amount that has cents. For example:
![Screenshot 2023-10-14 at 19 08 55](https://github.com/SolidInvoice/SolidInvoice/assets/113509/14f4db54-586d-4679-8f58-0e2ae29acee0)

3. Click on 'Update'
4. The saved invoice will remove the cent values from all line items. For example here:
![Screenshot 2023-10-14 at 19 09 06](https://github.com/SolidInvoice/SolidInvoice/assets/113509/77fa882a-f5d8-4b17-a146-3686855524d4)

**Expected behavior**
Preservation of the cent values in final invoice

**Desktop (please complete the following information):**
- OS: I tried https://solidinvoice.app as well as Docker image from https://hub.docker.com/r/solidinvoice/solidinvoice
- Browser: Chrome V. 117.0.5938.149
- Version 2.2.3

**Additional context**
I tried it with EUR and USD currency

**Comment by Nilson** [comment]
related to #293 ?

**Comment by pierredup** [comment]
This is fixed in #980 and will be included in the 2.2.6 release
